### ISSUE TITLE
Can't umount folder after downing container

### ISSUE THREAD

**Issue by kuritsynso** [gseldon/goofys#1]
After downing cantainer shit happend: ERROR: for s3fs  Cannot start service s3fs: error while creating mount source path '/opt/data-s3-tmp': mkdir /opt/data-s3-tmp: file exists. Help me! In this DIR is located a lot of info =(

**Comment by gseldon** [comment]
After disconnecting the containers, run the command:

`umount -l /opt/data-s3-tmp`

**Comment by kuritsynso** [comment]
Thank you!
